name: dream_navigation
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  bolter_flutter: ^6.7.2
  animator: ^3.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
