name: dream_navigation
description: I like this navigator, thats all...
version: 1.0.7
homepage: https://github.com/Renesanse/dream_navigation

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  bolter_flutter: ^6.8.1
  animator: ^3.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
